var actionTypes = {
  BEFORE_INITIALIZE: null,
  AFTER_INITIALIZE: null,
  ERROR_INITIALIZE: null,

  LOGOUT: null,

  BEFORE_MODIFY_PASSWORD: null,
  AFTER_MODIFY_PASSWORD: null,
  ERROR_MODIFY_PASSWORD: null,

  BEFORE_GET_CLIENTS: null,
  AFTER_GET_CLIENTS: null,
  ERROR_GET_CLIENTS: null,

  SET_CURRENT_CLIENT: null,

  BEFORE_CREATE_NEW_CLIENT: null,
  AFTER_CREATE_NEW_CLIENT: null,
  ERROR_CREATE_NEW_CLIENT: null,

  BEFORE_UPDATE_CLIENT: null,
  AFTER_UPDATE_CLIENT: null,
  ERROR_UPDATE_CLIENT: null,

  BEFORE_SEARCH_USER: null,
  AFTER_SEARCH_USER: null,
  ERROR_SEARCH_USER: null,

  BEFORE_RESET_USER_PASSWORD: null,
  AFTER_RESET_USER_PASSWORD: null,
  ERROR_RESET_USER_PASSWORD: null,

  BEFORE_GET_CONTAINERS: null,
  AFTER_GET_CONTAINERS: null,
  ERROR_GET_CONTAINERS: null,

  BEFORE_CREATE_NEW_CONTAINER: null,
  AFTER_CREATE_NEW_CONTAINER: null,
  ERROR_CREATE_NEW_CONTAINER: null,

  BEFORE_REMOVE_CONTAINER: null,
  AFTER_REMOVE_CONTAINER: null,
  ERROR_REMOVE_CONTAINER: null,
};

Object.keys(actionTypes).forEach(function(key) {
  actionTypes[key] = key;
});

export default actionTypes;
